name: clan
version: '1.0-SNAPSHOT'
main: org.perq.clan.Clan
api-version: '1.21'
softdepend:
  - PlaceholderAPI
commands:
  clan:
    description: "Clan commands"
    usage: "/clan <subcommand>"
    aliases: [clans, c]
  war:
    description: "Clan war commands"
    usage: "/war <subcommand>"

permissions:
  clan.default:
    description: "Allows basic clan commands"
    default: true
  clan.vip:
    description: "Allows creating clan tags with &6 color code"
    default: false
  clan.admin:
    description: "Allows admin clan commands (force leave, delete clans)"
    default: op
