name: clan
version: '1.0-SNAPSHOT'
main: org.perq.clan.Clan
api-version: '1.21'
softdepend:
  - PlaceholderAPI
commands:
  clan:
    description: "Clan Befehle"
    usage: "/clan <subcommand>"
    aliases: [clans, c]


